name: Github PR Audit

on: 
    pull_request:
        paths:
            - 'backend/**/*'
    check_run:
      types: [requested_action]
    # requested_action:
    #     identifier: heavy_task_requested

jobs:
      ## With actions
  request_action:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: LouisBrunner/checks-action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Heavy Task
        conclusion: action_required
        action_url: https://example.com/action
        # details_url: https://example.com/details
        actions: |
          [{"label":"Run action","description":"run expensive action manually","identifier":"heavy_task_requested"}]
  run_heavy_task:
    if: ${{ github.event_name == 'check_run' && github.event.action.identifier == 'heavy_task_requested' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo success
  always_runs:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo run